### ISSUE TITLE
Latest alpine/socat:1.7.3.4-r1 fails to resolve host.docker.internal

### ISSUE THREAD

**Issue by nickcaballero** [alpine-docker/socat#10]
Using socat for host.docker.internal works with 1.7.3.4-r0.

```
# start container
docker run --rm -p8080:8080 alpine/socat:1.7.3.4-r1 'TCP-LISTEN:8080,fork', 'TCP:host.docker.internal:8080'

# call it
curl localhost:8080

# log
socat[6] E getaddrinfo("host.docker.internal", "NULL", {1,0,1,6}, {}): Name does not resolve
```

**Comment by ozbillwang** [comment]
This repo is to do a simple job, install socat in alpine image and push it. I do not take responsibility for the functions in it.

If you found any bugs in this tool, please report to

socat@dest-unreach.org

https://repo.or.cz/socat.git

http://www.dest-unreach.org/socat/

**Comment by alphkn** [comment]
I have encountered similar problem. socat throws "name does not resolve" exception for "host.docker.internal" . I just downgraded alpine to version 3.11.5.
