### ISSUE TITLE
Latest 1.7.4.0-r0 release breaks "something"

### ISSUE THREAD

**Issue by dnephin** [alpine-docker/socat#11]
Unfortunately it's not clear to me what exactly is broken. We use this image in CI, and the `1.7.4.0-r0` tag appears to not cat everything. Our tests are grepping the output for some lines, and as soon as this new image started being used the lines were missing. 

Sorry I can't provide much more information, but I thought it may be helpful to someone.

We'll be pinning to one of the previous images for now. Reverting to the previous image makes the test pass again.

**Comment by ozbillwang** [comment]
Good point. Release candidate (*-rX) are not formal release. 

We shouldn't update `latest` tag for `*-ro`version.

**Comment by ozbillwang** [comment]
This repo is to do a simple job, install socat in alpine image and push it. I do not take responsibility for the functions in it. 

If you found any bugs in this tool, please report to 

socat@dest-unreach.org

https://repo.or.cz/socat.git

http://www.dest-unreach.org/socat/

**Comment by alphkn** [comment]
I have encountered similar problem. socat throws "name does not resolve" exception for "host.docker.internal" . I just downgraded alpine to version 3.11.5.
