### ISSUE TITLE
Upgrade socat to 1.7.4.1-r0

### ISSUE THREAD

**Issue by tomaspinho** [alpine-docker/socat#13]
socat 1.7.4.1-r0 is available on the Alpine package tracker. Would PRs to update the version in the image be acceptable?

**Comment by ozbillwang** [comment]
the schedule job would auto detect the latest version and install if not imaged. It runs daily, so normally wait for less than 24 hours, it will be there.

https://travis-ci.com/alpine-docker/socat

![image](https://user-images.githubusercontent.com/8954908/118750215-58440e80-b8a2-11eb-81eb-4242c80afe9a.png)
