### ISSUE TITLE
Update image on Docker Hub

### ISSUE THREAD

**Issue by brandond** [alpine-docker/socat#6]
The current image is about a year old. Would it be possible to rebuild and push with an up-to-date Alpine base and socat version?

**Comment by ozbillwang** [comment]
Could you raise a PR for it?

Which alpine version you prefer? How about `alpine:edge`?

**Comment by brandond** [comment]
It looks like it's just pulling from 'alpine:latest', which points at 3.10 at the moment which is fine. I don't think there are any changes that need to be made to the Dockerfile, it just needs to be built and pushed to Docker Hub again so that it can source the latest base image and package version. If there was way a way to set it up for auto-trigger builds, it might be nice to have that done every month or so just to keep up with security updates to Alpine.

**Comment by ozbillwang** [comment]
have built with latest socat. 

Will plan an auto-trigger build if there is a new socat version released.

**Comment by ozbillwang** [comment]
I have added `auto-trigger` feature to build the image when new release is available in alpine

### Daily build logs:

https://travis-ci.org/alpine-docker/socat

### Docker iamge tags:

https://hub.docker.com/r/alpine/socat/tags/
